name: Java TpsitProject CI

on:
  push:
    branches:
      - develop-MultiUser  # Trigger on push to develop-MultiUser
  pull_request:
    branches:
      - develop-MultiUser  # Trigger on pull request to develop-MultiUser

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Print directory structure for debugging
      - name: Print directory structure
        run: |
          ls -alh
          find .

      # Set up Java (adjust the version as needed)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # Run Maven build using the pom.xml in the root directory
      - name: Compile Java code
        run: mvn clean compile
