name: Java TpsitProject CI

on:
  push:
    paths:
      - 'TpsitProject-Java/**'
  pull_request:
    paths:
      - 'TpsitProject-Java/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TpsitProject-Java

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run tests
        run: mvn -B test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-tpsit-artifacts
          path: ./TpsitProject-Java/target/*.jar
          retention-days: 7
