name: Java TpsitProject CI

on:
  push:
    branches:
      - develop-MultiUser 
  pull_request:
    branches:
      - develop-MultiUser 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (adjust the version as needed)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Print directory structure for debugging
      - name: Print directory structure
        run: |
          ls -alh
          find .

      # Check for the presence of the pom.xml file
      - name: Ensure pom.xml is present
        run: |
          if [ ! -f "pom.xml" ]; then
            echo "No pom.xml found, please check your repository structure!"
            exit 1
          fi

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # If pom.xml is in a subdirectory (adjust the directory if necessary)
      - name: Compile Java code
        run: mvn clean compile

  formatting:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4  # v2 minimum required

      # Apply google-java-format to check and format code
      - name: Check and format Java code using google-java-format
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true

      # Print the diff of formatting changes (if any)
      - name: Print diffs
        run: git --no-pager diff --exit-code
